### ISSUE TITLE
Add edd to bioconda?

### ISSUE THREAD

**Issue by endrebak** [CollasLab/edd#8]
This would greatly simplify the installation. I made a few stabs at it, but was unable to get it to work:

https://travis-ci.org/bioconda/bioconda-recipes/builds/266776185

**Comment by dpryan79** [comment]
I've just added a recipe for release 1.1.18 to bioconda.

**Comment by endrebak** [comment]
Nice job! I'll try reading your recipe to understand where I went wrong.

**Comment by dpryan79** [comment]
@endrebak I expect you were only missing [this tweak](https://bioconda.github.io/troubleshooting.html#zlib-errors) (and that one of the tests returns a non-zero status on success).

**Comment by eivindgl** [comment]
Good work @endrebak and @dpryan79 
I had no idea that bioconda was a language agnostic package manager. It seems very useful!

**Comment by FatihSarigol** [comment]
Thanks guys for the conda build, but the current `1.1.19` version does not work, the similar error happens which was already posted:
https://github.com/CollasLab/edd/issues/12

`htslib` needs to be downgraded to this version so that it can be wrapped by `pysam` properly:

`conda install htslib=1.3.2`
